DROP TABLE IF EXISTS `paises`;
CREATE TABLE IF NOT EXISTS `paises` (
  `codpais` varchar(3) NOT NULL default '',
  `pais` varchar(30) default NULL,
  PRIMARY KEY  (`codpais`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `timezone`;
CREATE TABLE IF NOT EXISTS `timezone` (
  `timezoneid` int(11) NOT NULL auto_increment,
  `gmt_offset` double default '0',
  `dst_offset` double default NULL,
  `timezone_code` varchar(4) default NULL,
  `timezone` varchar(50) default NULL COMMENT 'Valor de la variable global TZ en PHP que cambia la zona horaria del servidor',
  `descripcion` varchar(100) NOT NULL,
  `activo` binary(1) NOT NULL default '1',
  PRIMARY KEY  (`timezoneid`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=76 ;

INSERT INTO `paises` (`codpais`, `pais`) VALUES
('AD', 'Andorra'),
('AE', 'Emiratos Arabes Unidos'),
('AF', 'Afganistan'),
('AG', 'Antigua y Barbuda, Islas'),
('AI', 'Anguilla, isla'),
('AL', 'Albania'),
('AM', 'Armenia'),
('AN', 'Antillas Holandesas, islas'),
('AO', 'Angola'),
('AQ', 'Antartida'),
('AR', 'Argentina'),
('AS', 'Samoa americana, isla'),
('AT', 'Austria'),
('AU', 'Australia'),
('AW', 'Aruba, isla'),
('AZ', 'Azerbayan'),
('BA', 'Bosnia y Hercegovina'),
('BB', 'Barbados, islas'),
('BD', 'Bangla Desh'),
('BE', 'Belgica'),
('BF', 'Burkina Faso'),
('BG', 'Bulgaria'),
('BH', 'Bahrein'),
('BI', 'Burundi'),
('BJ', 'Benin'),
('BM', 'Bermudas, islas'),
('BN', 'Brunei, sultanato'),
('BO', 'Bolivia'),
('BR', 'Brazil'),
('BS', 'Bahamas, islas'),
('BT', 'Butan'),
('BV', 'Bouvet, isla'),
('BW', 'Botsuana'),
('BY', 'Bielorrusia'),
('BZ', 'Belice'),
('CA', 'Canada'),
('CC', 'Cocos, isla (Keeling)'),
('CD', 'Congo, Republica popular'),
('CF', 'Centroafricana, Republica'),
('CG', 'Congo, Republica'),
('CH', 'Suiza'),
('CI', 'Costa de Marfil'),
('CK', 'Cook, Islas'),
('CL', 'Chile'),
('CM', 'Camerun'),
('CN', 'China'),
('CO', 'Colombia'),
('CR', 'Costa Rica'),
('CU', 'Cuba, isla'),
('CV', 'Cabo Verde, islas'),
('CX', 'Christmas, Islas'),
('CY', 'Chipre, isla'),
('CZ', 'Checa, Republica'),
('DE', 'Alemania'),
('DJ', 'Djibouti'),
('DK', 'Dinamarca'),
('DM', 'Dominica, isla'),
('DO', 'Dominicana, Republica'),
('DZ', 'Argelia'),
('EC', 'Ecuador'),
('EE', 'Estonia'),
('EG', 'Egipto'),
('EH', 'Sahara Occidental'),
('ER', 'Eritrea'),
('ES', 'España'),
('ET', 'Etiopia'),
('FI', 'Finlandia'),
('FJ', 'Fiyi, islas'),
('FK', 'Malvinas, islas'),
('FM', 'Micronesia, islas'),
('FO', 'Faroe, islas'),
('FR', 'Francia'),
('GA', 'Gabon'),
('GB', 'Reino Unido'),
('GD', 'Granada, islas'),
('GE', 'Georgia'),
('GF', 'Guayana francesa'),
('GH', 'Ghana'),
('GI', 'Gibraltar, PeÃ±on'),
('GL', 'Groenlandia'),
('GM', 'Gambia'),
('GN', 'Guinea'),
('GP', 'Guadelupe, islas (Fr.)'),
('GQ', 'Guinea Ecuatorial'),
('GR', 'Grecia'),
('GS', 'Sandwich del sur, islas'),
('GT', 'Guatemala'),
('GU', 'Guam, isla'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HK', 'Hong Kong, China'),
('HM', 'Heard y McDonald, islas'),
('HN', 'Honduras'),
('HR', 'Croacia'),
('HT', 'Haiti'),
('HU', 'Hungria'),
('ID', 'Indonesia'),
('IE', 'Irlanda'),
('IL', 'Israel'),
('IN', 'India'),
('IO', 'Islas del R.U. en el indic'),
('IQ', 'Iraq'),
('IR', 'Iran'),
('IS', 'Islandia'),
('IT', 'Italia'),
('JM', 'Jamaica, isla'),
('JO', 'Jordania'),
('JP', 'Japon'),
('KE', 'Kenia'),
('KG', 'Kirguizistan'),
('KH', 'Camboya'),
('KI', 'Kiribati, islas'),
('KM', 'Comores, islas'),
('KN', 'Saint Kitts y Nevis, islas'),
('KP', 'Korea del Norte'),
('KR', 'Korea del Sur'),
('KW', 'Kuwait'),
('KY', 'Caiman, islas'),
('KZ', 'Kazajstan'),
('LA', 'Laos, Republica'),
('LB', 'Libano'),
('LC', 'Santa Lucia, islas'),
('LI', 'Liechtenstein'),
('LK', 'Sri Lanka'),
('LR', 'Liberia'),
('LS', 'Lesotho'),
('LT', 'Lituania'),
('LU', 'Luxemburgo'),
('LV', 'Letonia'),
('LY', 'Libia'),
('MA', 'Marruecos'),
('MC', 'Monaco'),
('MD', 'Moldavia'),
('MG', 'Madagascar'),
('MH', 'Marshall, Islas'),
('MK', 'Macedonia'),
('ML', 'Mali'),
('MM', 'Myanmar (ex Birmania)'),
('MN', 'Mongolia'),
('MO', 'Macao, isla'),
('MP', 'Marianas, islas del norte'),
('MQ', 'Martinica, islas'),
('MR', 'Mauritania'),
('MS', 'Montserrat, isla'),
('MT', 'Malta, isla'),
('MU', 'Mauricio, islas'),
('MV', 'Maldivas, islas'),
('MW', 'Malawi'),
('MX', 'México'),
('MY', 'Malasia'),
('MZ', 'Mozambique'),
('NA', 'Namibia'),
('NC', 'Nueva Caledonia, isla'),
('NE', 'Niger'),
('NF', 'Norfolk, isla'),
('NG', 'Nigeria'),
('NI', 'Nicaragua'),
('NL', 'Paises Bajos (Holanda)'),
('NO', 'Noruega'),
('NP', 'Nepal'),
('NR', 'Nauru, isla'),
('NU', 'Niue, islas'),
('NZ', 'Nueva Zelandia'),
('OM', 'Oman'),
('PA', 'Panama'),
('PE', 'Perú'),
('PF', 'Polinesia francesa'),
('PG', 'Papua Nueva Guinea'),
('PH', 'Filipinas'),
('PK', 'Pakistan'),
('PL', 'Polonia'),
('PM', 'Pierre y Miquelon, islas'),
('PN', 'Pitcairn, islas'),
('PR', 'Puerto Rico'),
('PS', 'Palestina, territorios'),
('PT', 'Portugal'),
('PW', 'Palau, islas'),
('PY', 'Paraguay'),
('QA', 'Qatar'),
('RE', 'Reunion, islas'),
('RO', 'Rumania'),
('RU', 'Rusia, federacion'),
('RW', 'Ruanda'),
('SA', 'Arabia Saudi'),
('SB', 'Salomon, islas'),
('SC', 'Seychelles, islas'),
('SD', 'Sudan'),
('SE', 'Suecia'),
('SG', 'Singapur'),
('SH', 'Santa Helena, isla'),
('SI', 'Eslovenia'),
('SJ', 'Svalbard y Jan Mayen, isla'),
('SK', 'Eslovaquia'),
('SL', 'Sierra Leona'),
('SM', 'San Marino'),
('SN', 'Senegal'),
('SO', 'Somalia'),
('SR', 'Surinam'),
('ST', 'Sao Tome y Principe, islas'),
('SV', 'El Salvador'),
('SY', 'Siria'),
('SZ', 'Swazilandia'),
('TC', 'Turks y Ciacos, islas'),
('TD', 'Chad'),
('TF', 'Territorios de Francia en'),
('TG', 'Togo'),
('TH', 'Tailandia'),
('TJ', 'Tajikistan'),
('TK', 'Tokelau, islas'),
('TM', 'Turkmenistan'),
('TN', 'Tunez (Tunicia)'),
('TO', 'Tonga, islas'),
('TP', 'Timor del este'),
('TR', 'Turquia'),
('TT', 'Trinidad y Tobago'),
('TV', 'Tuvalu, islas'),
('TW', 'Taiwan, China'),
('TZ', 'Tanzania'),
('UA', 'Ucrania'),
('UG', 'Uganda'),
('UM', 'Islas menores de USA'),
('US', 'Estados Unidos'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VA', 'Vaticano, ciudad estado'),
('VC', 'San Vincente y Granadinas'),
('VE', 'Venezuela'),
('VG', 'Virgines, Islas (British)'),
('VI', 'Virgines, Islands (USA)'),
('VN', 'Vietnam'),
('VU', 'Vanuatu, islas'),
('WF', 'Wallis y Futuna, islas'),
('WS', 'Samoa Occidental, isla'),
('YE', 'Yemen'),
('YT', 'Mayotte, isla'),
('YU', 'Yugoslavia'),
('ZA', 'Sudafrica'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');

INSERT INTO `timezone` (`timezoneid`, `gmt_offset`, `dst_offset`, `timezone_code`, `timezone`, `descripcion`, `activo`) VALUES
(1, -12, 0, NULL, 'Etc/GMT-12', '(GMT-12:00) International Date Line West', '1'),
(2, -11, 0, 'SST', 'Pacific/Samoa', '(GMT-11:00) Midway Island Samoa', '1'),
(3, -10, 0, 'H', 'Pacific/Honolulu', '(GMT-10:00) Hawaii', '1'),
(4, -9, 1, 'AK', 'America/Juneau', '(GMT-09:00) Alaska', '1'),
(5, -8, 1, 'P', 'America/Los_Angeles', '(GMT-08:00) Pacific Time (US & Canada); Tijuana', '1'),
(6, -7, 0, 'MDT', 'America/Phoenix', '(GMT-07:00) Arizona', '1'),
(7, -7, 1, 'MDT', 'America/Chihuahua', '(GMT-07:00) Chihuahua, La Paz, Mazatlan', '1'),
(8, -7, 1, 'MDT', 'America/Denver', '(GMT-07:00) Mountain Time (US & Canada)', '1'),
(9, -6, 0, 'CT', 'America/Costa_Rica', '(GMT-06:00) Central America', '1'),
(10, -6, 1, 'CST', 'America/Chicag', '(GMT-06:00) Central Time (US & Canada)', '1'),
(11, -6, 1, NULL, 'America/Mexico_City', '(GMT-06:00) Guadalajara, Mexico City, Monterrey', '1'),
(12, -6, 0, 'C', 'America/Winnipeg', '(GMT-06:00) Saskatchewan', '1'),
(13, -5, 0, NULL, 'America/Bogota', '(GMT-05:00) Bogota, Lime, Quito', '1'),
(14, -5, 1, 'E', 'America/New_York', '(GMT-05:00) Eastern Time (US & Canada)', '1'),
(15, -5, 0, 'E', 'America/Indianapolis', '(GMT-05:00) Indiana (East)', '1'),
(16, -4, 1, 'A', 'America/Halifax', '(GMT-04:00) Atlantic Time (Canada)', '1'),
(17, -4, 0, NULL, 'America/Caracas', '(GMT-04:00) Caracas, La Paz', '1'),
(18, -4, 1, NULL, 'America/Santiago', '(GMT-04:00) Santiago', '1'),
(19, -3.5, 1, 'N', 'America/St_Johns', '(GMT-03:30) Newfoundland', '1'),
(20, -3, 1, NULL, 'America/Sao_Paulo', '(GMT-03:00) Brasilia', '1'),
(21, -3, 0, NULL, 'America/Buenos_Aires', '(GMT-03:00) Buenos Aires, Georgetown', '1'),
(22, -3, 1, NULL, 'America/Thule', '(GMT-03:00) Greenland', '1'),
(23, -2, 1, NULL, 'Atlantic/South_Georgia', '(GMT-02:00) Mid-Atlantic', '1'),
(24, -1, 1, NULL, 'Atlantic/Azores', '(GMT-01:00) Azores', '1'),
(25, -1, 0, NULL, 'Atlantic/Cape_Verde', '(GMT-01:00) Cape Verde Is.', '1'),
(26, 0, 0, NULL, 'Africa/Casablanca', '(GMT) Casablanca, Monrovia', '1'),
(27, 0, 1, NULL, 'Europe/Dublin', '(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London', '1'),
(28, 1, 1, NULL, 'Europe/Amsterdam', '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', '1'),
(29, 1, 1, NULL, 'Europe/Belgrade', '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', '1'),
(30, 1, 1, NULL, 'Europe/Brussels', '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris', '1'),
(31, 1, 1, NULL, 'Europe/Warsaw', '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb', '1'),
(32, 1, 0, NULL, 'Africa/Lagos', '(GMT+01:00) West Central Africa', '1'),
(33, 2, 1, NULL, 'Europe/Athens', '(GMT+02:00) Athens, Istanbul, Minsk', '1'),
(34, 2, 1, NULL, 'Europe/Bucharest', '(GMT+02:00) Bucharest', '1'),
(35, 2, 1, NULL, 'Africa/Cairo', '(GMT+02:00) Cairo', '1'),
(36, 2, 0, NULL, 'Africa/Harare', '(GMT+02:00) Harare, Pretoria', '1'),
(37, 2, 1, NULL, 'Europe/Helsinki', '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', '1'),
(38, 2, 0, NULL, 'Asia/Jerusalem', '(GMT+02:00) Jerusalem', '1'),
(39, 3, 1, NULL, 'Asia/Baghdad', '(GMT+03:00) Baghdad', '1'),
(40, 3, 0, NULL, 'Asia/Kuwait', '(GMT+03:00) Kuwait, Riyadh', '1'),
(41, 3, 1, NULL, 'Europe/Moscow', '(GMT+03:00) Moscow, St. Petersburg, Volgograd', '1'),
(42, 3, 0, NULL, 'Africa/Nairobi', '(GMT+03:00) Nairobi', '1'),
(43, 3.5, 1, NULL, 'Asia/Tehran', '(GMT+03:30) Tehran', '1'),
(44, 4, 0, NULL, 'Asia/Dubai', '(GMT+04:00) Abu Dhabi, Muscat', '1'),
(45, 4, 1, NULL, 'Asia/Baku', '(GMT+04:00) Baku, Tbilisi, Yerevan', '1'),
(46, 4.5, 0, NULL, 'Asia/Kabul', '(GMT+04:30) Kabul', '1'),
(47, 5, 1, NULL, 'Asia/Yekaterinburg', '(GMT+05:00) Ekaterinburg', '1'),
(48, 5, 0, NULL, 'Asia/Karachi', '(GMT+05:00) Islamabad, Karachi, Tashkent', '1'),
(49, 5.5, 0, NULL, 'Asia/Calcutta', '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi', '1'),
(50, 5.75, 0, NULL, 'Asia/Katmandu', '(GMT+05.75) Kathmandu', '1'),
(51, 6, 1, NULL, 'Asia/Almaty', '(GMT+06:00) Almaty, Novosibirsk', '1'),
(52, 6, 0, NULL, 'Asia/Dhaka', '(GMT+06:00) Astana, Dhaka', '1'),
(53, 6, 0, NULL, 'Asia/Colombo', '(GMT+06:00) Sri Jayawardenepura', '1'),
(54, 6.5, 0, NULL, 'Asia/Rangoon', '(GMT+06:30) Rangoon', '1'),
(55, 7, 0, NULL, 'Asia/Bangkok', '(GMT+07:00) Bangkok, Hanoi, Jakarta', '1'),
(56, 7, 1, NULL, 'Asia/Krasnoyarsk', '(GMT+07:00) Krasnoyarsk', '1'),
(57, 8, 0, NULL, 'Asia/Hong_Kong', '(GMT+08:00) Beijing, Chongging, Hong Kong, Urumgi', '1'),
(58, 8, 1, NULL, 'Asia/Irkutsk', '(GMT+08:00) Irkutsk, Ulaan Bataar', '1'),
(59, 8, 0, NULL, 'Asia/Kuala_Lumpur', '(GMT+08:00) Kuala Lumpur, Singapore', '1'),
(60, 8, 0, NULL, 'Australia/Perth', '(GMT+08:00) Perth', '1'),
(61, 8, 0, NULL, 'Asia/Taipei', '(GMT+08:00) Taipei', '1'),
(62, 9, 0, NULL, 'Asia/Tokyo', '(GMT+09:00) Osaka, Sapporo, Tokyo', '1'),
(63, 9, 0, NULL, 'Asia/Seoul', '(GMT+09:00) Seoul', '1'),
(64, 9, 1, NULL, 'Asia/Yakutsk', '(GMT+09:00) Yakutsk', '1'),
(65, 9.5, 1, NULL, 'Australia/Adelaide', '(GMT+09:30) Adelaide', '1'),
(66, 9.5, 0, NULL, 'Australia/Adelaide', '(GMT+09:30) Darwin', '1'),
(67, 10, 0, NULL, 'Australia/Brisbane', '(GMT+10:00) Brisbane', '1'),
(68, 10, 1, NULL, 'Australia/Sydney', '(GMT+10:00) Canberra, Melbourne, Sydney', '1'),
(69, 10, 0, NULL, 'Pacific/Guam', '(GMT+10:00) Guam, Port Moresby', '1'),
(70, 10, 1, NULL, 'Australia/Hobart', '(GMT+10:00) Hobart', '1'),
(71, 10, 1, NULL, 'Asia/Vladivostok', '(GMT+10:00) Vladivostok', '1'),
(72, 11, 0, NULL, 'Asia/Magadan', '(GMT+11:00) Magadan, Solomon Is., New Caledonia', '1'),
(73, 12, 1, NULL, 'Pacific/Auckland', '(GMT+12:00) Auckland, Wellington', '1'),
(74, 12, 0, NULL, 'Pacific/Fiji', '(GMT+12:00) Figi, Kamchatka, Marshall Is.', '1'),
(75, 13, 0, NULL, 'Pacific/Tongatapu', '(GMT+13:00) Nuku alofa', '1');

